n1 = float(input("What is n1? "))
phat1 = float(input("What is phat1? "))
n2 = float(input("What is n2? "))
phat2 = float(input("What is phat2? "))
print()
print("n1phat1:     " + str(n1*phat1))
print("n1(1-phat1): " + str(n1*(1-phat1)))
print("n2phat2:     " + str(n2*phat2))
print("n2(1-phat2): " + str(n2*(1-phat2)))